name: Run Postman Tests

on:
  push:
    branches:
      - main  # Замените на имя вашей ветки, если это не main
  pull_request:
    branches:
      - main  # Замените на имя вашей ветки, если это не main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu для запуска тестов

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Настроим Node.js
        with:
          node-version: '16'  # Используем Node.js версии 16

      - name: Install Newman
        run: npm install -g newman  # Устанавливаем Newman глобально

      - name: Run Postman Collection Tests
        run: newman run ./TEST.postman_collection.json
